spring:
    application:
        name: service2
    profiles:
        active: dev
    config:
        import: optional:configserver:http://localhost:9000

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8888/eureka
management:
    tracing:
        sampling:
            probability: 1.0
        propagation:
            consume: b3
            produce: b3_multi
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans

logging:
    pattern:
        level: "%5p [%X{TraceId:-},%X{spanId:-}]"
